### ISSUE TITLE
Provide profile button

### ISSUE THREAD

**Issue by littlejohnjt** [Schlagen-Management/FitnessLeaderBoard#24]

**Comment by ninedesign** [comment]
Will need a better solution, there is no space for a profile button. I will work on a one-screen pop-up/tutorial on the app that explains how to use the widget. People are used to click/tap on their image for the profile info, we just need to educate them.

**Comment by littlejohnjt** [comment]
What about a hamburger menu?  Or a gear icon in the top corner in the header with the app title?

Just thoughts


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by littlejohnjt** [comment]
Call if you want to discuss


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
